export type AtariSpriteId =
  | 'agente-j'
  | 'lia'
  | 'nodo-rec'
  | 'onda-for'
  | 'anomalia-ssa'
  | 'sistema-anac'
  | 'glitch-jpa'
  | 'glitch-nat'
  | 'glitch-the'
  | 'glitch-bel'
  | 'glitch-mao'
  | 'glitch-gyn'
  | 'glitch-cnf'
  | 'glitch-vix'
  | 'glitch-gig'
  | 'glitch-cgh'
  | 'glitch-gru'
  | 'glitch-cwb'
  | 'glitch-fln'
  | 'glitch-poa'
  | 'glitch-pvh'
  | 'glitch-rbr';

export type AtariSprite = {
  id: AtariSpriteId;
  rows: string[];
  palette: Record<string, number>;
};

const BLACK = 0x000000;
const WHITE = 0xf8f8f8;
const SKIN = 0xd89048;
const SKIN_LIGHT = 0xf0b068;
const HAIR = 0x302018;
const NAVY = 0x2848a8;
const CYAN = 0x30c8d8;
const RED = 0xd82828;
const ORANGE = 0xe87020;
const YELLOW = 0xf8d848;
const GREEN = 0x48d860;
const BLUE = 0x2868d8;
const MAGENTA = 0xb840d8;
const DARK_GRAY = 0x303030;

const characterPalette = {
  A: HAIR,
  B: SKIN,
  C: SKIN_LIGHT,
  D: NAVY,
  E: CYAN,
  F: BLACK,
  G: WHITE,
  H: RED,
};

export const ATARI_SPRITES: Record<AtariSpriteId, AtariSprite> = {
  'agente-j': {
    id: 'agente-j',
    palette: characterPalette,
    rows: [
      '......AAAAAA......',
      '.....AAAAAAAA.....',
      '....AABBBBBAA.....',
      '...AABCCCCBBA.....',
      '...ABCGFFGCBA.....',
      '...ABCFFFFCBA.....',
      '...ABCCCCCCBA.....',
      '....AABGGBBA......',
      '.....EABBBE.......',
      '.....EEBBEE.......',
      '....DDDEEDDD......',
      '...DDDEDDDEDD.....',
      '..DDDEDDDDDEDD....',
      '..DDDDDEEDDDD.....',
      '..DDDHDFFDHDD.....',
      '...DDDDFFDDDD.....',
      '....DDDFFDDD......',
      '.....DD..DD.......',
      '.....DD..DD.......',
      '.....DD..DD.......',
      '.....DD..DD.......',
      '.....FF..FF.......',
      '....FFF..FFF......',
      '...FFFF..FFFF.....',
    ],
  },
  lia: {
    id: 'lia',
    palette: {
      ...characterPalette,
      I: ORANGE,
      J: YELLOW,
    },
    rows: [
      '.....AAAAAAAA.....',
      '....AAAAAAAAAA....',
      '...AAABBBBBAAA....',
      '...AABCCCCBBAA....',
      '..AAACGFFGCAAA....',
      '..AAACFFFFCAAA....',
      '...AABCCCCBBA.....',
      '....AAJJJJAA......',
      '......BBBB........',
      '.....IIIIII.......',
      '....IIJIIJII......',
      '...IIJIIIIJII.....',
      '..IIIJJIIJJIII....',
      '..IIIIIIIIIIII....',
      '..IIJIIHHIIJII....',
      '...IIIIHHIIII.....',
      '....IIIIIIII......',
      '.....II..II.......',
      '.....II..II.......',
      '.....II..II.......',
      '.....II..II.......',
      '.....FF..FF.......',
      '....FFF..FFF......',
      '...FFFF..FFFF.....',
    ],
  },
  'nodo-rec': {
    id: 'nodo-rec',
    palette: {
      R: RED,
      O: ORANGE,
      Y: YELLOW,
      G: GREEN,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '.....RRRRRR.....',
      '...RRRYYYYRRR...',
      '..RRYYRRRRYYRR..',
      '..RYRRGGWWRRYR..',
      '..RYRRDDDD RYR..',
      '..RRYYRRRRYYRR..',
      '...RRRYYYYRRR...',
      '.....RRRRRR.....',
      '.......RR.......',
      '....RRRRRRRR....',
      '..RRROOOOOORRR..',
      '.RROODDDDDDOORR.',
      '.RRODGGDDGGDORR.',
      '..RROODDDDOORR..',
      '....RRRRRRRR....',
      '...RR..RR..RR...',
    ],
  },
  'onda-for': {
    id: 'onda-for',
    palette: {
      C: CYAN,
      B: BLUE,
      W: WHITE,
      R: RED,
      O: ORANGE,
    },
    rows: [
      '...CCCC....CCCC.',
      '..CCBBCC..CCBBCC',
      '.CCBBBBCCCCBBBB.',
      'CCBBWWBBBBWWBBC',
      '.CBBBBBBBBBBBBC.',
      '..CCBBBBBBBBCC..',
      '....CCBBBBCC....',
      'CCCC..CCCC..CCCC',
      'BBBBCCCCCCCCBBBB',
      '...BBRRRRRRBB...',
      '..BBRROOOORRBB..',
      '..BRROWWWWORRB..',
      '...BBRRRRRRBB...',
      'CCCC..CCCC..CCCC',
      '.BBBBCCCCCCCCBB.',
      '..CCCC....CCCC..',
    ],
  },
  'anomalia-ssa': {
    id: 'anomalia-ssa',
    palette: {
      M: MAGENTA,
      R: RED,
      O: ORANGE,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '..MMMMMMMMMMMM..',
      '.MMRRRRRRRRRRMM.',
      'MMRROOOOOOOORRMM',
      'MRROWWOWWOWORRM.',
      'MRROOOOOOOOORRM.',
      'MMRRDDDDDDRRMM..',
      '.MMMMMMMMMMMM...',
      '...MM....MM.....',
      '..MMMR..RMMM....',
      '.MMRMRRRRMRMM...',
      'MMRMMRRRRMMRMM..',
      'MRRMMRWWRMMRRM..',
      'MMRMMRRRRMMRMM..',
      '.MMRMRRRRMRMM...',
      '..MMMMMMMMMM....',
      '...MM....MM.....',
    ],
  },
  'sistema-anac': {
    id: 'sistema-anac',
    palette: {
      G: GREEN,
      C: CYAN,
      W: WHITE,
      R: RED,
      D: DARK_GRAY,
      Y: YELLOW,
    },
    rows: [
      '...GGGGGGGGGG...',
      '..GGCCCCCCCCGG..',
      '.GGCCWWCCWWCCGG.',
      '.GCCDDCCCCDDCCG.',
      '.GCCCCRRRRCCCCG.',
      '.GGCCCCCCCCCCGG.',
      '..GGGGGGGGGGGG..',
      '....GG....GG....',
      '..GGGGYYYYGGGG..',
      '.GGDGGYYYYGGDGG.',
      'GGDDGGYYYYGGDDGG',
      'GDDDGGRRRRGGDDDG',
      'GGDDGGYYYYGGDDGG',
      '.GGDGGYYYYGGDGG.',
      '..GGGGGGGGGGGG..',
      '....GG....GG....',
    ],
  },
  'glitch-jpa': {
    id: 'glitch-jpa',
    palette: {
      C: CYAN,
      B: BLUE,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '................',
      '......CCCC......',
      '....CCBBBBCC....',
      '...CBBWWWWBBCC..',
      '..CBWWCCCCWWBC..',
      '..CBWCDDDDCWBC..',
      '..CBWWCCCCWWBC..',
      '...CBBWWWWBBC...',
      '....CCBBBBCC....',
      '......CCCC......',
      '................',
      '....DDDDDDDD....',
      '....D......D....',
      '....DDDDDDDD....',
      '................',
      '................',
    ],
  },
  'glitch-nat': {
    id: 'glitch-nat',
    palette: {
      R: RED,
      O: ORANGE,
      Y: YELLOW,
      D: DARK_GRAY,
    },
    rows: [
      'RR..............',
      '.RR.........OO..',
      '..RR.......OO...',
      '...RR.....OO....',
      '....RR...OO.....',
      '.....RR.OO......',
      '......RROO......',
      '.....OOYYRR.....',
      '....OO...RR.....',
      '...OO.....RR....',
      '..OO.......RR...',
      '.OO.........RR..',
      'OO...........RR.',
      'DDDDDDDDDDDDDDDD',
      'DDDDDDDDDDDDDDDD',
      '................',
    ],
  },
  'glitch-the': {
    id: 'glitch-the',
    palette: {
      B: BLUE,
      C: CYAN,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '................',
      '......WWWW......',
      '....WWBBBBWW....',
      '...WBBCCCCBBW...',
      '..WBCCWWWWCCBW..',
      '.WBCWWBBBBWWCBW.',
      'WBCWBBCCCCBBWCBW',
      'BCWBCCCDDCCCBWCB',
      'WBCWBBCCCCBBWCBW',
      '.WBCWWBBBBWWCBW.',
      '..WBCCWWWWCCBW..',
      '...WBBCCCCBBW...',
      '....WWBBBBWW....',
      '......WWWW......',
      '................',
      '................',
    ],
  },
  'glitch-bel': {
    id: 'glitch-bel',
    palette: {
      B: BLUE,
      C: CYAN,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '................',
      '.CCC........CCC.',
      'CBBBCC....CCBBBC',
      'CBWWBC....CBWWBC',
      'CBBBCC....CCBBBC',
      '.CCC........CCC.',
      '................',
      '......DDDD......',
      '.....DBBBBD.....',
      '.....DBWWBD.....',
      '.....DBBBBD.....',
      '......DDDD......',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'glitch-mao': {
    id: 'glitch-mao',
    palette: {
      O: ORANGE,
      Y: YELLOW,
      D: DARK_GRAY,
      W: WHITE,
    },
    rows: [
      '................',
      '................',
      '................',
      'OOOO......OOOOOO',
      'YYYY......YYYYYY',
      'OOOO......OOOOOO',
      'DDDD......DDDDDD',
      '................',
      '....YYYYYYYY....',
      '...YOOOOOOOOY...',
      '..YODDDDDDDDOY..',
      '...YOOOOOOOOY...',
      '....YYYYYYYY....',
      '................',
      '................',
      '................',
    ],
  },
  'glitch-gyn': {
    id: 'glitch-gyn',
    palette: {
      Y: YELLOW,
      O: ORANGE,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '................',
      '.Y..Y..YY..Y..Y.',
      '.YY.Y..YY..Y.YY.',
      '..YYYYYYYYYYY...',
      '...YYYYYYYYY....',
      '....YYYYYYY.....',
      '.....YYYYY......',
      '....OOOOOOO.....',
      '....OWWWWWO.....',
      '....OWDDWWO.....',
      '....OWWWWWO.....',
      '....OOOOOOO.....',
      '.....OOOOO......',
      '......OOO.......',
      '.......O........',
      '................',
    ],
  },
  'glitch-cnf': {
    id: 'glitch-cnf',
    palette: {
      G: GREEN,
      D: DARK_GRAY,
      Y: YELLOW,
      W: WHITE,
    },
    rows: [
      '......GGG.......',
      '.....GGGGG......',
      '..GG.GGGGG.GG...',
      '.GGGG.GGG.GGGG..',
      '..GGG.GGG.GGG...',
      '...GGGGGGGGG....',
      '....GGGGGGG.....',
      '......GGG.......',
      '......GDG.......',
      '......GDG.......',
      '.GGG..GDG..GGG..',
      'GDDGG.GDG.GGDDG.',
      '.GGGG.GDG.GGGG..',
      '......GDG.......',
      '......GDG.......',
      '......YYY.......',
    ],
  },
  'glitch-vix': {
    id: 'glitch-vix',
    palette: {
      C: CYAN,
      B: BLUE,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '................',
      '................',
      'WWWW....WWWW....',
      '.WWWWWWWWWWW....',
      '..BBBBBBBBB.....',
      '...BBBBBBB......',
      'CCCC....CCCC....',
      '.CCCCCCCCCC.....',
      '..BBBBBBBB......',
      '...BBBBBB.......',
      'WWWW....WWWW....',
      '.WWWWWWWWWWW....',
      '..BBBBBBBBB.....',
      '...BBBBBBB......',
      '................',
      '................',
    ],
  },
  'glitch-gig': {
    id: 'glitch-gig',
    palette: {
      M: MAGENTA,
      Y: YELLOW,
      R: RED,
      C: CYAN,
      O: ORANGE,
      W: WHITE,
    },
    rows: [
      '....Y......M....',
      '...YY......MM...',
      '..YOY......MRM..',
      'M......YY......R',
      'MM....YWWY....RR',
      '.M....YWWY....R.',
      '......CWWC......',
      '......CWWC......',
      '.R....MWWM....Y.',
      'RR....MCCM....YY',
      'R......MM......Y',
      '..CMC......YOY..',
      '...CM......YY...',
      '....C......Y....',
      '................',
      '................',
    ],
  },
  'glitch-cgh': {
    id: 'glitch-cgh',
    palette: {
      R: RED,
      O: ORANGE,
      Y: YELLOW,
      D: DARK_GRAY,
      W: WHITE,
    },
    rows: [
      'RRRRRRRRRRRRRRRR',
      'ROOOOOOOOOOOOOOR',
      'RRRRRRRRRRRRRRRR',
      '................',
      'OOOOOOOOOOOOOOOO',
      'OYYYYYYYYYYYYYO',
      'OOOOOOOOOOOOOOOO',
      '................',
      'RRRRRRRRRRRRRRRR',
      'RWWWWWWWWWWWWWWR',
      'RRRRRRRRRRRRRRRR',
      '................',
      'DDDDDDDDDDDDDDDD',
      'DRRRRRRRRRRRRRRD',
      'DDDDDDDDDDDDDDDD',
      '................',
    ],
  },
  'glitch-gru': {
    id: 'glitch-gru',
    palette: {
      R: RED,
      O: ORANGE,
      D: DARK_GRAY,
      W: WHITE,
    },
    rows: [
      'R.R.R.R.R.R.R.R.',
      '.R.R.R.R.R.R.R.R',
      'R.ROOOOOOOOO.R.R',
      '.R.OWWWWWWWO.R..',
      'R.R.OWWRRWWO.R.R',
      '.R..OWROORWO.R..',
      'R.R.OWROORWO.R.R',
      '.R..OWWRRWWO..R.',
      'R.R.OWWWWWWO.R.R',
      '.R.OOOOOOOOOO.R.',
      'R.R..........R.R',
      '.R.RRRRRRRRRR.R.',
      'R.R.R.R.R.R.R.R.',
      '.R.R.R.R.R.R.R.R',
      'R.R.R.R.R.R.R.R.',
      '.R.R.R.R.R.R.R.R',
    ],
  },
  'glitch-cwb': {
    id: 'glitch-cwb',
    palette: {
      W: WHITE,
      D: DARK_GRAY,
      C: CYAN,
      B: BLUE,
    },
    rows: [
      '................',
      '....WWWWWWWW....',
      '..WWWWWWWWWWWW..',
      '.WWWWDDDDDWWWWW.',
      'WWWWDDWDDWDDWWWW',
      'WWWWDWWWWWDWWWWW',
      'WWWWDWCWCWDWWWWW',
      'WWWWDWWBWWDWWWWW',
      'WWWWDWCWCWDWWWWW',
      'WWWWDWWWWWDWWWWW',
      'WWWWDDWWWDDWWWWW',
      '.WWWWWWWWWWWWWW.',
      '..WWWWWWWWWWWW..',
      '....WWWWWWWW....',
      '................',
      '................',
    ],
  },
  'glitch-fln': {
    id: 'glitch-fln',
    palette: {
      D: DARK_GRAY,
      B: BLUE,
      W: WHITE,
      C: CYAN,
    },
    rows: [
      'DDDDDDDDDDDDDDDD',
      'D.DDDDDDDDDDDD.D',
      'D..DDDDDDDDDD..D',
      'D...DDDDDDDD...D',
      'D....DDDDDD....D',
      'D..B..DDDD..B..D',
      'D..BB..DD..BB..D',
      'D..BBB.WW.BBB..D',
      'D..BBBBWWBBBB..D',
      'D...BBBCCBBB...D',
      'D....BBCCBB....D',
      'D.....BCCB.....D',
      'D......CC......D',
      'D.......C......D',
      'D..............D',
      'DDDDDDDDDDDDDDDD',
    ],
  },
  'glitch-poa': {
    id: 'glitch-poa',
    palette: {
      C: CYAN,
      B: BLUE,
      W: WHITE,
      D: DARK_GRAY,
    },
    rows: [
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '.CCCCCCCCCCCCCC.',
      'C......CC......C',
      'C.....CCCC.....C',
      'B....BBBBBB....B',
      'B...BB....BB...B',
      'D..DD......DD..D',
      'D.DD........DD.D',
      'W.W..........W.W',
      '................',
    ],
  },
  'glitch-pvh': {
    id: 'glitch-pvh',
    palette: {
      D: DARK_GRAY,
      R: RED,
      W: WHITE,
      O: ORANGE,
    },
    rows: [
      'DDDDDDDDDDDDDDDD',
      'DRRRRRRRRRRRRRD',
      'DRDDDDDDDDDDDRD',
      'DRDWWWWWWWWWDRD',
      'DRDWDDDDDDWDRD.',
      'DRDWDDDDDDWDRD.',
      'DRDWDDDDDDWDRD.',
      'DRDWWWWWWWWDRD.',
      'DRDDDDDDDDDDDRD',
      'DRRRRRRRRRRRRD.',
      'DDDDDDDDDDDDDD.',
      '................',
      'OOOOOOOOOOOOOOOO',
      'O..............O',
      'OOOOOOOOOOOOOOOO',
      '................',
    ],
  },
  'glitch-rbr': {
    id: 'glitch-rbr',
    palette: {
      D: DARK_GRAY,
      W: WHITE,
      R: RED,
      C: CYAN,
    },
    rows: [
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '........C.......',
      '.......DDD......',
      '......DWWWD.....',
      '......DRRRD.....',
      '......DWWWD.....',
      '.......DDD......',
      '................',
      '................',
      '................',
    ],
  },
};

export function getAtariSprite(id: AtariSpriteId): AtariSprite {
  return ATARI_SPRITES[id];
}

export function getSpriteMetrics(sprite: AtariSprite): { width: number; height: number } {
  return {
    width: Math.max(...sprite.rows.map(row => row.length)),
    height: sprite.rows.length,
  };
}
